import Foundation

public enum Flag: String, Codable {
    case afghanistan
    case angola
    case albania
    case andorra
    case unitedArabEmirates
    case argentina
    case armenia
    case antiguaAndBarbuda
    case australia
    case austria
    case azerbaijan
    case burundi
    case belgium
    case benin
    case burkinaFaso
    case bangladesh
    case bulgaria
    case bahrain
    case bahamas
    case bosniaAndHerzegovina
    case belarus
    case belize
    case bolivia
    case brazil
    case barbados
    case bruneiDarussalam
    case bhutan
    case botswana
    case centralAfricanRepublic
    case canada
    case switzerland
    case chile
    case china
    case cTeDIvoire
    case cameroon
    case democraticRepublicOfTheCongo
    case republicOfTheCongo
    case colombia
    case comoros
    case capeVerde
    case costaRica
    case cuba
    case cyprus
    case czechRepublic
    case germany
    case djibouti
    case dominica
    case denmark
    case dominicanRepublic
    case algeria
    case ecuador
    case egypt
    case eritrea
    case spain
    case estonia
    case ethiopia
    case finland
    case fiji
    case france
    case micronesiaFederatedStatesOf
    case gabon
    case unitedKingdom
    case georgia
    case ghana
    case guinea
    case gambia
    case guineaBissau
    case equatorialGuinea
    case greece
    case grenada
    case guatemala
    case guyana
    case honduras
    case croatia
    case haiti
    case hungary
    case indonesia
    case india
    case ireland
    case iranIslamicRepublicOf
    case iraq
    case iceland
    case israel
    case italy
    case jamaica
    case jordan
    case japan
    case kazakhstan
    case kenya
    case kyrgyzstan
    case cambodia
    case kiribati
    case saintKittsAndNevis
    case southKorea
    case kuwait
    case laoPeopleSDemocraticRepublic
    case lebanon
    case liberia
    case libya
    case saintLucia
    case liechtenstein
    case sriLanka
    case lesotho
    case lithuania
    case luxembourg
    case latvia
    case morocco
    case monaco
    case moldova
    case madagascar
    case maldives
    case mexico
    case marshallIslands
    case northMacedonia
    case mali
    case malta
    case myanmar
    case montenegro
    case mongolia
    case mozambique
    case mauritania
    case mauritius
    case malawi
    case malaysia
    case namibia
    case niger
    case nigeria
    case nicaragua
    case netherlands
    case norway
    case nepal
    case nauru
    case newZealand
    case oman
    case pakistan
    case panama
    case peru
    case philippines
    case palau
    case papuaNewGuinea
    case poland
    case northKorea
    case portugal
    case paraguay
    case qatar
    case romania
    case russia
    case rwanda
    case saudiArabia
    case sudan
    case senegal
    case singapore
    case solomonIslands
    case sierraLeone
    case elSalvador
    case sanMarino
    case somalia
    case serbia
    case southSudan
    case saoTomeAndPrincipe
    case suriname
    case slovakia
    case slovenia
    case sweden
    case eswatini
    case seychelles
    case syria
    case chad
    case togo
    case thailand
    case tajikistan
    case turkmenistan
    case timorLeste
    case tonga
    case trinidadAndTobago
    case tunisia
    case turkey
    case tuvalu
    case tanzania
    case uganda
    case ukraine
    case uruguay
    case unitedStates
    case uzbekistan
    case vaticanCity
    case saintVincentAndTheGrenadines
    case venezuela
    case vietnam
    case vanuatu
    case samoa
    case yemen
    case southAfrica
    case zambia
    case zimbabwe

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
}
